name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Build the Go application
      - name: Build application
        run: |
          go build -o myapp

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Push Docker image to Docker Hub (or any registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker tag myapp:latest <your-dockerhub-username>/myapp:latest
          docker push <your-dockerhub-username>/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy the container
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << EOF
            docker pull <your-dockerhub-username>/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 8080:8080 --name myapp <your-dockerhub-username>/myapp:latest
          EOF
