name: CI/CD for Go Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    # Step 3: Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Step 4: Run tests
    - name: Run tests
      run: go test ./...

    # Step 5: Build Docker image
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/go-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/go-app:latest
